# Generated by Django 3.2.12 on 2023-07-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank_profile_pic.png', upload_to='profile_images'),
        ),
    ]
